apiVersion: apps/v1
kind: Deployment
metadata:
  name: agriculture-api
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: api
        env:
        - name: DEBUG
          value: "true"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
