apiVersion: apps/v1
kind: Deployment
metadata:
  name: agriculture-api
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: api
        env:
        - name: DEBUG
          value: "false"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
